module.exports = {
    'market-intelligence-api': {
        input: 'http://localhost:8080/api/v3/api-docs',
        output: {
            schemas: "src/generated/market-intelligence-api/dtos",
            target: "src/generated/market-intelligence-api/hook.ts",
            clean: true,
            override: {
                header: ({title, description, version}) => [
                    `Generated by orval`,
                    `Do not edit manually.`,
                    ...(title ? [title] : []),
                    ...(description ? [description] : []),
                    ...(version ? [`OpenAPI spec version: ${version}`] : []),
                ]
            },
        },
    },
};
