name: Deploy Backend

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./market-intelligence-api
jobs:
  build:
    runs-on: [self-hosted, testolo-server]
    steps:
      - uses: actions/checkout@v3 #To checkout the repo
      - name: Change right on mvn command
        run: chmod 755 ./mvnw
      - name: Build Maven
        run: ./mvnw package -Dmaven.test.skip=true
      - name: Move .jar to deployment directory
        run: mv ./target/market-intelligence-api-0.0.1-SNAPSHOT.jar /var/tmp/app.jar
      - name: Restart Java Server
        run: sudo systemctl restart nginx
