name: Deploy Frontend

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./market-intelligence-frontend
jobs:
  build:
    runs-on: [self-hosted, testolo-server]
    steps:
      - uses: actions/checkout@v3 #To checkout the repo
      - name: Install project
        run: npm install
      - name: Build project
        run: npm run build
      - name: Erase all file in the frontend directory
        run: rm -rf /var/tmp/frontend
      - name: Move the generated file to the frontend directory
        run: mv ./build/* /var/tmp/frontend/
